package com.lym.distributed.entity;

import java.util.Date;

public class DistributedUniqueNoConf {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_distributed_unique_no_conf.biz_tag
     *
     * @mbg.generated
     */
    private String bizTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_distributed_unique_no_conf.max_id
     *
     * @mbg.generated
     */
    private Long maxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_distributed_unique_no_conf.step
     *
     * @mbg.generated
     */
    private Integer step;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_distributed_unique_no_conf.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_distributed_unique_no_conf.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_distributed_unique_no_conf.biz_tag
     *
     * @return the value of p_distributed_unique_no_conf.biz_tag
     *
     * @mbg.generated
     */
    public String getBizTag() {
        return bizTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_distributed_unique_no_conf.biz_tag
     *
     * @param bizTag the value for p_distributed_unique_no_conf.biz_tag
     *
     * @mbg.generated
     */
    public void setBizTag(String bizTag) {
        this.bizTag = bizTag == null ? null : bizTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_distributed_unique_no_conf.max_id
     *
     * @return the value of p_distributed_unique_no_conf.max_id
     *
     * @mbg.generated
     */
    public Long getMaxId() {
        return maxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_distributed_unique_no_conf.max_id
     *
     * @param maxId the value for p_distributed_unique_no_conf.max_id
     *
     * @mbg.generated
     */
    public void setMaxId(Long maxId) {
        this.maxId = maxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_distributed_unique_no_conf.step
     *
     * @return the value of p_distributed_unique_no_conf.step
     *
     * @mbg.generated
     */
    public Integer getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_distributed_unique_no_conf.step
     *
     * @param step the value for p_distributed_unique_no_conf.step
     *
     * @mbg.generated
     */
    public void setStep(Integer step) {
        this.step = step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_distributed_unique_no_conf.description
     *
     * @return the value of p_distributed_unique_no_conf.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_distributed_unique_no_conf.description
     *
     * @param description the value for p_distributed_unique_no_conf.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_distributed_unique_no_conf.update_time
     *
     * @return the value of p_distributed_unique_no_conf.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_distributed_unique_no_conf.update_time
     *
     * @param updateTime the value for p_distributed_unique_no_conf.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}